name: Forbes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch
  - torchvision
  - numpy
  - pillow
  - scikit-image
  - pip:
    - opencv-python
    - scipy
    - matplotlib
    - tqdm
